---

- name: Get the hostname
  shell: hostname -f
  register: hostname

- name: "Check if Backdrop has been installed already"
  lineinfile:
    name: /var/aegir/admin/web/settings.php
    line: "database_name"
    state: present
  check_mode: yes
  register: settings

- name: Install Backdrop
  become: true
  become_user: aegir
  shell:
    chdir: "{{ aegir_home }}/admin/web"
    # bee does not work well for the site install, obscure errors
    cmd: "php ./core/scripts/install.sh --db-url='mysql://{{ aegir_db_name }}:{{ aegirpass.stdout }}@{{ aegir_db_host }}/{{ aegir_db_name }}' --account-name='admin' --account-mail='{{ aegir_admin_email }}' --site-name='{{ hostname.stdout }}'"
  when: settings.changed

# FIXME: this is a workaround because our common vhost stuff aliases /files to /sites/xx/files
# but maybe we should not use that common vhost
- name: Create a dummy site directory because of the Aegir vhost
  file:
    path: "{{ aegir_home }}/admin/web/sites/{{ hostname.stdout }}"
    state: directory
    mode: 0775
    owner: "{{ aegir_user }}"
    group: "{{ aegir_web_group }}"

- name: Create a symbolic link for the files directory
  ansible.builtin.file:
    src: "{{ aegir_home }}/admin/web/files"
    dest: "{{ aegir_home }}/admin/web/sites/{{ hostname.stdout }}/files"
    owner: "{{ aegir_user }}"
    group: "{{ aegir_web_group }}"
    state: link

- name: Fix the files directory permissions
  file:
    path: "{{ aegir_home }}/admin/files"
    state: directory
    mode: 0775
    owner: "{{ aegir_user }}"
    group: "{{ aegir_web_group }}"

- name: Set the site frontpage to hosting/sites
  become: true
  become_user: aegir
  shell:
    chdir: "{{ aegir_home }}/admin/web"
    cmd: "bee config-set system.core site_frontpage hosting/sites"
