---

# Remove the Drupal10 core cron

- name: Check if the cms core cron currently exists
  stat:
    path: "/etc/systemd/system/d7corecron_{{ site_shortname }}.service"
  register: timer

- name: Stop the cms core cron timer
  systemd:
    name: "d7corecron_{{ site_shortname }}.timer"
    state: stopped
  when: timer.stat.exists

- name: Delete the cms core cron service
  file:
    path: "/etc/systemd/system/d7corecron_{{ site_shortname }}.service"
    state: absent

- name: Delete the cms core cron timer
  file:
    path: "/etc/systemd/system/d7corecron_{{ site_shortname }}.timer"
    state: absent
  notify: reload systemd

# In theory this should not be necessary, but it seems that regardless of
# the order in which services are disabled/removed, systemd is unhappy and
# flags the old service as failed
- name: Systemd reset-failed
  ansible.builtin.command: systemctl reset-failed
  when: timer.stat.exists
