---

- hosts: all
  tasks:
    - name: Run CMS-specific tasks
      include_tasks: "verify/{{ software }}.yml"

    - name: Update the platform status
      shell:
        chdir: "/var/aegir/admin/web"
        cmd: "/usr/local/bin/bee hosting-platform-update-status --status=1 {{ nid }}"
