---

- hosts: all
  tasks:
    - name: Generate a filename for the backup using the timestamp
      shell: "echo {{ inventory_hostname }}-$(date +%Y%m%d%H%M%S).tar"
      register: filename

    - name: Change the site directory permissions temporarily
      file:
        path: "{{ site_path }}"
        state: directory
        mode: 0750

    - name: Drupal10 | Generate a database dump
      shell:
        chdir: "{{ site_path }}"
        cmd: "drush -l {{ inventory_hostname }} sql-dump --result-file={{ site_path }}/database.sql"
        creates: "{{ site_path }}/database.sql"
      become: true
      become_user: aegir
      when: software == "Drupal10"

    - name: Backdrop | Generate a database dump
      shell:
        chdir: "{{ site_path }}"
        cmd: "bee sql-dump {{ site_path }}/database.sql"
        creates: "{{ site_path }}/database.sql"
      become: true
      become_user: aegir
      when: software == "Backdrop"

    - name: WordPress | Generate a database dump
      shell:
        chdir: "{{ site_path }}"
        cmd: "wp db export {{ site_path }}/database.sql"
        creates: "{{ site_path }}/database.sql"
      become: true
      become_user: aegir
      when: software == "WordPress"

    - name: Remove DEFINERs for views and procedures
      shell:
        chdir: "{{ site_path }}"
        cmd: "perl -i -pe 's#\\/\\*\\!5001[7|3].*?`[^\\*]*\\*\\/##g;' -pe 's/DEFINER=[^ ]+//g' ./database.sql"
      become: true
      become_user: aegir

    - name: Drupal10 | Run fix permissions
      shell:
        chdir: "{{ site_path }}"
        cmd: "/usr/local/aegir-ansible-playbooks/bin/fix-drupal-permissions.sh --site-path='{{ site_path }}'"
      tags:
        - drupal-fixpermissions
      when: software == "Drupal10"

    - name: tar all files
      shell:
        chdir: "{{ site_path }}"
        cmd: "tar cpf /var/aegir/backups/{{ filename.stdout }} ."

  # TODO: exclude directories

    - name: Delete the local SQL dump
      file:
        path: "{{ site_path }}/database.sql"
        state: absent

    - name: Change the site directory permissions back to normal
      file:
        path: "{{ site_path }}"
        state: directory
        mode: 0550

    # We check stdout because bee does not exit non-zero on errors
    - name: Store the filename of the backup in the frontend
      shell:
        chdir: "/var/aegir/admin/web"
        cmd: "/usr/local/bin/bee hosting-site-backup {{ nid }} {{ filename.stdout }} {{ task }}"
      register: result
      failed_when: "result.stdout != ''"
      become: true
      become_user: aegir
