---

- hosts: all
  tasks:
    - name: Change the source site directory permissions temporarily
      file:
        path: "{{ site_path }}"
        state: directory
        mode: 0750

    - include_tasks: "backup/sql.yml"

    - name: rsync the site to the new location
      ansible.posix.synchronize:
        src: "{{ site_path }}/"
        dest: "{{ new_site_root }}/sites/{{ new_uri }}"
        archive: true

    - name: Delete the local SQL dump
      file:
        path: "{{ site_path }}/database.sql"
        state: absent

    - name: Change the source site directory permissions back to normal
      file:
        path: "{{ site_path }}"
        state: directory
        mode: 0550

    - name: Register a new site in the Aegir inventory
      shell:
        chdir: "/var/aegir/admin/web"
        cmd: "/usr/local/bin/bee hosting-site-clone {{ nid }} {{ new_uri }} {{ target_platform }} {{ new_db_server }}"
      register: result
      failed_when: "'^\\d+' not in result.stdout"

    - name: Create the new MySQL database and user
      include_tasks: "install/mysql.yml"

    - name: Test if a database.sql file already exists (clone or remote-import)
      stat:
        path: "{{ site_path }}/database.sql"
      register: sqldump

    - name: Update CMS-specific settings
      include_tasks: "verify/{{ software }}/settings.yml"
      when: sqldump.stat.exists

    - name: Import the SQL dump
      include_tasks: "restore/sql.yml"
      when: sqldump.stat.exists
