---

- hosts: all
  tasks:
    - name: Register a new site in the Aegir inventory
      shell:
        chdir: "/var/aegir/admin/web"
        cmd: "/usr/local/bin/bee hosting-site-clone {{ inventory_hostname }} {{ new_uri }} {{ target_platform }} {{ new_db_server }}"

    - name: Change the site directory permissions temporarily
      file:
        path: "{{ site_path }}"
        state: directory
        mode: 0750

    - include_tasks: "backup/sql.yml"

    # TODO rsync files
    # Import SQL (in install.yml?)

    - name: Delete the local SQL dump
      file:
        path: "{{ site_path }}/database.sql"
        state: absent

    - name: Change the site directory permissions back to normal
      file:
        path: "{{ site_path }}"
        state: directory
        mode: 0550
