---

- hosts: all
  tasks:
    - name: Update the site status to Disabled
      shell:
        chdir: "/var/aegir/admin/web"
        cmd: "/usr/local/bin/bee hosting-site-update-status --status=-1 {{ nid }}"

    # Not sure if necessary, or other weird bug
    - name: Flush the cache
      shell:
        chdir: "/var/aegir/admin/web"
        cmd: "/usr/local/bin/bee cc core"

    - name: Run provision-verify to update the vhost
      shell:
        chdir: "/var/aegir/admin/web"
        cmd: "/usr/local/bin/bee hosting-site-task {{ inventory_hostname }} verify"

  handlers:
  - name: reload nginx
    service:
      name: nginx
      state: reloaded
