---

- hosts: all
  tasks:
     - name: Create the new MySQL database and user
       include_tasks: "install/mysql.yml"
 
     - name: Test if a database.sql file already exists (clone or remote-import)
       stat:
         path: "{{ site_path }}/database.sql"
       register: sqldump
 
     - name: Update CMS-specific settings
       include_tasks: "verify/{{ software }}/settings.yml"
       when: sqldump.stat.exists
 
     - name: Import the SQL dump
       include_tasks: "restore/sql.yml"
       when: sqldump.stat.exists
