---

- hosts: all
  tasks:
    # Ignore the directory permissions for now, we only change it when necessary
    - name: Create the site directory
      file:
        path: "{{ site_path }}"
        state: directory
        owner: aegir
        group: www-data

    - name: Create the MySQL database
      mysql_db:
        name: "{{ db_name }}"
        state: present
        login_user: "{{ hostvars[db_host]['db']['db_user'] }}"
        login_password: "{{ hostvars[db_host]['db']['db_passwd'] }}"

    - name: Create the MySQL user
      mysql_user:
        name: "{{ db_name }}"
        password: "{{ db_passwd }}"
        priv:
          '{{ db_name }}.*:ALL'
        column_case_sensitive: true
        state: present
        login_user: "{{ hostvars[db_host]['db']['db_user'] }}"
        login_password: "{{ hostvars[db_host]['db']['db_passwd'] }}"

    - name: Run CMS-specific tasks
      include_tasks: "install/{{ software }}.yml"

    - name: Run provision-enable
      shell:
        chdir: "/var/aegir/admin/web"
        cmd: "/usr/local/bin/bee hosting-site-task {{ inventory_hostname }} enable"
