---

- hosts: all
  tasks:
    # Ignore the directory permissions for now, we only change it when necessary
    - name: Create the site directory
      file:
        path: "{{ site_path }}"
        state: directory
        owner: aegir
        group: www-data

    - name: Create the new MySQL database and user
      include_tasks: "install/mysql.yml"

    - name: Run CMS-specific installation tasks
      include_tasks: "install/{{ software }}.yml"

    - name: Run the post-install command
      shell:
        cmd: "{{ hostvars[platform_name]['site_post_install_cmd'] }}"
      when: hostvars[platform_name]['site_post_install_cmd'] | length > 0

    - name: Run provision-enable
      shell:
        chdir: "/var/aegir/admin/web"
        cmd: "/usr/local/bin/bee hosting-site-task {{ inventory_hostname }} enable"
      # @todo 'bee' does not return errors, validate output
      # failed_when: "'^\\d+' not in result.stdout"
