---

- hosts: all
  tasks:

    - name: Create the temporary site restore directory
      file:
        path: "{{ site_path }}.restore"
        state: directory
        owner: aegir
        group: www-data

    - name: Untar the backup
      shell:
        chdir: "{{ site_path }}.restore"
        cmd: "tar xf /var/aegir/backups/{{ backup_filename }} --exclude='civicrm.settings.php' --exclude='settings.php' --exclude='drushrc.php' --exclude='wp-config.php'"
        creates: "{{ site_path }}.restore/database.sql"

    - name: Delete the site directory
      file:
        path: "{{ site_path }}"
        state: absent

    - name: Move the restore temporary directory as the new site directory
      shell:
        cmd: "mv {{ site_path }}.restore {{ site_path }}"
        creates: "{{ site_path }}"

    - name: Run CMS-specific verify tasks
      include_tasks: "verify/{{ software }}.yml"

    - name: Import the SQL dump
      include_tasks: "restore/sql.yml"

    - name: Delete the SQL dump
      file:
        path: "{{ site_path }}/database.sql"
        state: absent

  handlers:
  - name: reload nginx
    service:
      name: nginx
      state: reloaded

  - name: reload systemd
    systemd:
      daemon_reload: yes
