---

- hosts: all
  vars_files:
    - defaults.yml
  tasks:
    - name: Check if the http cert already exists
      stat:
        path: "/var/lib/dehydrated/certs/{{ inventory_hostname }}/fullchain.pem"
      register: cert

    - name: Check if the dhparams file exists
      stat:
        path: "/etc/nginx/params.4096"
      register: dhparams

    - name: Create the nginx vhost
      template:
        src: "vhost-nginx.conf"
        dest: "/var/aegir/config/server_master/nginx/vhost.d/{{ inventory_hostname }}"
        owner: root
        group: root
        mode: 0644
      notify:
        - reload nginx

    - name: Force the nginx reload to happen now so that the well-known route works
      meta: flush_handlers

    - name: Run dehydrated
      include_tasks: "verify/dehydrated.yml"

    - name: Check again if the http cert exists
      stat:
        path: "/var/lib/dehydrated/certs/{{ inventory_hostname }}/fullchain.pem"
      register: cert

    - name: Update the nginx vhost again for https
      template:
        src: "vhost-nginx.conf"
        dest: "/var/aegir/config/server_master/nginx/vhost.d/{{ inventory_hostname }}"
        owner: root
        group: root
        mode: 0644
      notify:
        - reload nginx

    - name: Create a drush site alias file for legacy scripts such as monitoring
      template:
        src: "site.alias.drushrc.php.j2"
        dest: "/var/aegir/.drush/{{ inventory_hostname }}.alias.drushrc.php"
        owner: aegir
        group: aegir
        mode: 0644

    - name: Run CMS-specific tasks
      include_tasks: "verify/{{ software }}.yml"

    - name: Run the post-verify command
      shell:
        cmd: "{{ hostvars[platform_name]['site_post_verify_cmd'] }}"
      when: hostvars[platform_name]['site_post_verify_cmd'] | length > 0

    - name: Update the site verified status
      shell:
        chdir: "/var/aegir/admin/web"
        cmd: "/usr/local/bin/bee hosting-site-update-status --verified=1 {{ nid }}"
      register: result
      failed_when: "result.stdout != ''"
      become: true
      become_user: aegir

  handlers:
  - name: reload nginx
    service:
      name: nginx
      state: reloaded

  - name: reload systemd
    systemd:
      daemon_reload: yes
