---

- hosts: all
  tasks:
    - name: Check if the http cert already exists
      stat:
        path: "/var/aegir/config/letsencrypt.d/{{ inventory_hostname }}/fullchain.pem"
      register: cert

    - name: Check if the dhparams file exists
      stat:
        path: "/etc/nginx/params.4096"
      register: dhparams

    - name: Create the nginx vhost
      template:
        src: "vhost-nginx.conf"
        dest: "/var/aegir/config/server_master/nginx/vhost.d/{{ inventory_hostname }}"
        owner: root
        group: root
        mode: 0644
      notify:
        - reload nginx

    - name: Force the nginx reload to happen now so that the well-known route works
      meta: flush_handlers

    - name: Generate an https certificate
      shell:
        chdir: "/var/aegir"
        cmd: "dehydrated --accept-terms -c -d {{ inventory_hostname }} -f /var/aegir/config/letsencrypt/config"
      register: certlog

    # Always display the output, often requires debugging
    - debug: var=certlog.stdout_lines

    - name: Check again if the http cert exists
      stat:
        path: "/var/aegir/config/letsencrypt.d/{{ inventory_hostname }}/fullchain.pem"
      register: cert

    - name: Update the nginx vhost again for https
      template:
        src: "vhost-nginx.conf"
        dest: "/var/aegir/config/server_master/nginx/vhost.d/{{ inventory_hostname }}"
        owner: root
        group: root
        mode: 0644
      notify:
        - reload nginx

    - name: Run CMS-specific tasks
      include_tasks: "verify/{{ software }}.yml"

  handlers:
  - name: reload nginx
    service:
      name: nginx
      state: reloaded

  - name: reload systemd
    systemd:
      daemon_reload: yes
