---

# nb: this is also included from 'aegir/admin/install/vhost.yml'
# hence the templates directory is under here too

# This was previously under /var/aegir/config/nginx.conf
# but we are trying to be a bit more standard and eventually phase out /var/aegir/conf
- name: Deploy our nginx aegir.conf
  ansible.builtin.template:
    src: "etc/nginx/conf.d/{{ item }}"
    dest: "/etc/nginx/conf.d/{{ item }}"
    owner: "root"
    group: "root"
    mode: "0644"
  with_items:
    - aegir.conf
    - z-aegir.conf

- name: Create the server_master vhost.d directory
  ansible.builtin.file:
    path: "/var/aegir/config/server_master/nginx/vhost.d/"
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Create the includes directory
  ansible.builtin.file:
    path: "/var/aegir/config/includes/"
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Deploy our nginx vhost includes
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "/var/aegir/config/includes/{{ item }}"
    owner: "root"
    group: "root"
    mode: "0644"
  with_items:
    - nginx_vhost_common.conf
    - nginx_vhost_aegir.conf
    - nginx_vhost_robotstxt.conf
