---

- name: "Upgrade Aegir"
  hosts: all
  vars:
    aegir_user: aegir
    aegir_home: /var/aegir
  tasks:
    - include_tasks: "../admin/install/bee.yml"

    - include_tasks: "upgrade-aegir/backdrop-core.yml"

    - name: Update the hosting module using git pull
      ansible.builtin.command: "git pull"
      args:
        chdir: "{{ aegir_home }}/admin/web/modules/hosting"
      become: true
      become_user: "{{ aegir_user }}"
      notify:
        - restart hosting-queued

    - name: Update the Aegir site database
      shell:
        chdir: "{{ aegir_home }}/admin/web"
        cmd: "/usr/local/bin/bee updb -y"
      become_user: "{{ aegir_user }}"

    # We never set the maintenance mode, but if the db upgrade fails, it will set it
    - name: Take site out of maintenance mode
      shell:
        chdir: "{{ aegir_home }}/admin/web"
        cmd: "/usr/local/bin/bee maintenance-mode 0"
      become_user: "{{ aegir_user }}"

    - name: Clear Backdrop caches
      shell:
        chdir: "{{ aegir_home }}/admin/web"
        cmd: "/usr/local/bin/bee cc all"
      become_user: "{{ aegir_user }}"

    - name: Queue a server verify task
      shell:
        chdir: "{{ aegir_home }}/admin/web"
        cmd: "/usr/local/bin/bee hosting-server-verify"

  handlers:
  - name: restart hosting-queued
    ansible.builtin.service:
      name: hosting-queued
      state: restarted
