---

- name: "Server verify"
  hosts: all
  vars:
    aegir_user: aegir
  tasks:
    - name: Run CMS-specific tasks
      ansible.builtin.include_tasks: "verify/nginx.yml"

    - name: Create symlinks for Aegir helper scripts
      ansible.builtin.file:
        src: "/usr/local/aegir-ansible-playbooks/bin/{{ item }}"
        dest: "/usr/local/bin/{{ item }}"
        force: true
        owner: "root"
        group: "root"
        state: "link"
      with_items:
        - cvlog
        - aegir-weekly.sh

    - name: Run provision-verify on the Aegir frontend
      shell:
        chdir: "/var/aegir/admin/web"
        cmd: "/usr/local/bin/bee hosting-site-task {{ aegir_frontend }} verify"

# todo:
# - validate MySQL credentials
