---

- name: "Server verify"
  hosts: all
  tasks:
    - name: Run CMS-specific tasks
      ansible.builtin.include_tasks: "verify/nginx.yml"

    - name: Create symlinks for Aegir helper scripts
      ansible.builtin.file:
        src: "/usr/local/aegir-ansible-playbooks/bin/{{ item }}"
        dest: "/usr/local/bin/{{ item }}"
        force: true
        owner: "root"
        group: "root"
        state: "link"
      with_items:
        - cv

# todo:
# - validate MySQL credentials
