# Aegir web server main configuration file
# These statements run last, so that we can add other confs.#
#
# {{ ansible_managed }}

#######################################################
###  nginx default server
#######################################################

# Default plain http vhost
server {
  listen *:80;
  listen [::]:80;
  server_name  _;
  default_type text/plain;
  return 404 "404 Not Found\n";
}

# Default HTTPS vhost
server {
  listen 443 ssl http2 default_server;
  listen [::]:443 ssl http2 default_server;
  server_name _;
  # Avoid trying to resume a previous https connection
  # https://serverfault.com/a/946287
  ssl_session_tickets off;
  # Rejects SSL handshakes for unrecognized domains
  # https://serverfault.com/a/1127589
  ssl_reject_handshake on;
}

#######################################################
###  nginx virtual domains
#######################################################

# virtual hosts
include /var/aegir/config/server_master/nginx/pre.d/*;
include /var/aegir/config/server_master/nginx/platform.d/*;
include /var/aegir/config/server_master/nginx/vhost.d/*;
include /var/aegir/config/server_master/nginx/post.d/*;
